version: "3.8"

services:
  app:
    build: .
    container_name: yt-app
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped