version: "3.8"

services:
  app:
    build: .
    container_name: yt-app
    ports: 
      - "5005:5005"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: yt-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: yt-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
      --email yasmina.attiallah@helloelho.com
      --agree-tos
      --no-eff-email
      -d helloelho.com -d www.helloelho.com && certbot renew"